### ISSUE TITLE
로그아웃 기능

### ISSUE THREAD

**Issue by tmdtmdqorekf** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_21_BE#33]
## ❓ 간략한 기능 설명

> 로그아웃 하는 기능입니다.

## 📋작업 상세 내용

- [ ] TODO
- [ ] TODO
- [ ] TODO

**Comment by Lujaec** [comment]
로그아웃은 프론트에서 저장했던 JWT를 삭제하면 돼서 서버에서 해야할 건 따로 없을 듯 !?

**Comment by tmdtmdqorekf** [comment]
아 확인확인! 이슈 닫을게~
